Update remote-resources for Jetty 11.
jetty/jetty-toolchain pull request #252
Opened 2023-05-03 15:13 UTC by joakime

+ Removed LICENSE as it refers to old EPL1
+ Replaced with LICENSE.md with EPL2 + ASL2
+ Renamed NOTICE.txt to NOTICE.md to conform to current Eclipse Foundation norms.
+ Updated content in NOTICE.md
+ Updated about.html, but I think it can be deleted as we are not "delivered as Eclipse Platform Plug-ins and Fragments" as outlined in https://www.eclipse.org/legal/epl/about.php

2023-05-03 15:15 UTC, joakime commented
Note that this version is only really applicable for Jetty 11.
The contents of the NOTICE.md will be different in Jetty 12 (as it include all of ee8, ee9, and ee10)
I wouldn't mind pulling this into the Jetty 11 build itself, and not relying on jetty.toolchain for this content.

2023-05-03 15:32 UTC, jmcc0nn3ll requested changes
What happened to putting this into the relevant jetty projects and not using the remote artifact resource?

Also, I think we can get rid of the about.html. If it is an issue for the platform consuming jetty through their p2 repositories, they can tackle that problem.

2023-05-03 15:42 UTC, joakime commented
> How about we just leave the `jetty-artifact-remote-resources` project alone, and ensure that we change any project that is using it to have it's own NOTICES/LICENCES file? I don't think it makes sense to have this kind of blanket approach to generating these files, considering how important they've become over the years.

This proposal is a way bigger hassle IMO.

That literally means we have `NOTICE.md` and `LICENSE.md` is copied to every single module's `src/main/resources/META-INF/` directory.
Keep in mind that these remote-resources are used by all of our produced (and deployed) artifacts, from things like jetty-util to things like apache-jsp.

2023-05-03 15:43 UTC, joakime commented on jetty-artifact-remote-resources/src/main/resources/META-INF/NOTICE.md
> +SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
Lets get the language right first.
Then we can merge it here and move it en-masse without changes in content to the locations where we need it (the jetty project produced artifacts in all of the various repos we have)

2023-05-03 16:24 UTC, janbartel commented
> > How about we just leave the `jetty-artifact-remote-resources` project alone, and ensure that we change any project that is using it to have it's own NOTICES/LICENCES file? I don't think it makes sense to have this kind of blanket approach to generating these files, considering how important they've become over the years.
> 
> This proposal is a way bigger hassle IMO.
> 
> That literally means we have `NOTICE.md` and `LICENSE.md` is copied to every single module's `src/main/resources/META-INF/` directory. Keep in mind that these remote-resources are used by all of our produced (and deployed) artifacts, from things like jetty-util to things like apache-jsp.

Sheesh, that _is_ a PITA. So we need to maintain at least 4 different versions: for jetty-9, 10, 11, 12?

2023-05-03 16:26 UTC, janbartel commented
I definitely think the `java-schemas` project needs to have it's own LICENCE and NOTICES files - all of the stuff about ow2, glassfish etc etc is just not applicable.

2023-05-03 16:37 UTC, joakime commented
That's how I see it ...

Jetty 9
  - javax.[spec]
  - asm on old and new license (depends on asm version)
  - apache jsp 
  - apache jstl
  - old EE specs on:
    - CDDL + GPL2+CPE
    - BSD-3-Claus
    - ASL2  (eg: javax.security.auth.message 1.x)

Jetty 10
  - javax.[spec]
  - asm on new license
  - apache jsp / jstl
  - jakarta EE specs:
    - EPL2 + GPL2+CPE
    - BSD-3-Clause
    - ASL2 (eg: javax.security.auth.message 1.x)

Jetty 11
  - jakarta.[spec]
  - asm on new license
  - apache jsp
  - glassfish jstl
  - jakarta EE specs
    - EPL2 + GPL2+CPE (many specs in transition here, some moved to this, eg javax.security.auth.message 2.x)
    - BSD-3-Clause
    - ASL2 (but far less)

Jetty 12
  - asm on new license
  - _ee8_
    - javax.[spec] - Jakarta EE8 versions
      - CDDL + GPL2+CPE
      - BSD-3-Claus
      - ASL2  (eg: javax.security.auth.message 1.x)
    - apache jsp
    - apache jstl
  - _ee9_
    - jakarta.[spec]
      - CDDL + GPL2+CPE
      - BSD-3-Claus
      - ASL2  (eg: javax.security.auth.message 1.x)
    - apache jsp
    - apache jstl
  - _ee10_
    - jakarta.[spec]
      - CDDL + GPL2+CPE
      - BSD-3-Claus
      - ASL2  (but far fewer)
    - apache jsp
    - glassfish jstl
   
And that's just what I've discovered so far.

2023-12-18 19:31 UTC, joakime commented
Closing, no longer relevant to this repo, or Jetty 11.

2023-12-18 19:31 UTC, closed without merging